name: Bourse Filter Alert

on:
  schedule:
    - cron: "*/10 5-9 * * 6,0,1,2,3"
  workflow_dispatch:

jobs:
  run-filter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install pytse-client pandas requests

      - name: Run filter script
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python bourse_filter_alert.py
